FROM bjdhub.haihangyun.com/openshift/origin-logging-fluentd:v3.6.0

#RUN rm /etc/fluent/fluent.conf
#COPY fluent.conf /etc/fluent/fluent.conf

#COPY input-pre-ha.conf /etc/fluent/configs.d/openshift/ 
#COPY output-pre-ha.conf  /etc/fluent/configs.d/openshift/ 
RUN  gem install -V fluentd-ui
